# http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/server/main.go
  env:
  - CGO_ENABLED=0
  ldflags:
    - -X main.appVersion={{.Version}} -X  main.appBuild={{.ShortCommit}}
  ignore:
    - goos: darwin
      goarch: arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
