apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zero-notification-service.fullname" . }}
data:
    SERVICE_PORT: {{ .Values.service.port }}
    GRACEFUL_SHUTDOWN_TIMEOUT_SECONDS: {{ .Values.application.gracefulShutdownTimeout }}
    STRUCTURED_LOGGING: {{ .Values.application.structuredLogging }}
