{{- if .Values.externalSecret.enabled -}}
{{- $fullName := include "zero-notification-service.fullname" . -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
spec:
  backendType: {{ .Values.externalSecret.backendType }}
  {{- if .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- .Values.externalSecret.dataFrom | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
