apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-notification-service.fullname" . }}
data:
type: Opaque
data:
  SENDGRID_API_KEY: {{ .Values.application.sendgridApiKey | b64enc | quote }}
