{{- if not .Values.externalSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-notification-service.fullname" . }}
data:
type: Opaque
data:
  SENDGRID_API_KEY: {{ .Values.application.sendgridApiKey | b64enc | quote }}
  SLACK_API_KEY: {{ .Values.application.slackApiKey | b64enc | quote }}
  TWILIO_ACCOUNT_ID: {{ .Values.application.twilioAccountID | b64enc | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.application.twilioAuthToken | b64enc | quote }} 
{{- end }}
