/*
 * Zero Notification Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/commitdev/zero-notification-service/internal/server"
	"github.com/commitdev/zero-notification-service/internal/service"
)

func main() {
	log.Printf("Server started")

	EmailApiService := service.NewEmailApiService()
	EmailApiController := server.NewEmailApiController(EmailApiService)

	HealthApiService := service.NewHealthApiService()
	HealthApiController := server.NewHealthApiController(HealthApiService)

	NotificationApiService := service.NewNotificationApiService()
	NotificationApiController := server.NewNotificationApiController(NotificationApiService)

	router := server.NewRouter(EmailApiController, HealthApiController, NotificationApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
